---
abstract: 'PayPal NVP API'
author:
  - 'Brad Haywood <brad@geeksware.com>'
  - 'Brad Haywood <brad@geeksware.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-PayPal-NVP
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  LWP::UserAgent: 0
  Moo: 0
  URI::Escape: 0
  perl: 5.6.0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.002
